---
- include_tasks: install.yml
  when: docker_install | bool
  
- include_tasks: config.yml

- import_tasks: docker-service.yml
  when: 
    - ansible_service_mgr == 'systemd' 
    - docker_http_proxy != "" or docker_https_proxy != "" or docker_no_proxy != ""
  
- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- include_tasks: docker-users.yml
  when: docker_users | length > 0
